---
- name: Insall java and net tools
  hosts: webserver
  become: yes
  tasks:
    - name: Update app repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install Java version 8
      apt: name=openjdk-11-jdk
    - name: Inatall net tools
      apt: name=net-tools



- name: Download and Unpack Nexus installer
  hosts: webserver
  become: yes
  tasks:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    # - debug: msg={{download_result}}

    - name: Untar nexus installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes

    - name: Find Nexus folder 
      find:
        path: /opt/
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    # - debug: msg={{find_result}}

    - name: Check nexus folder stats
      stat:
        path: /opt/nexus
      register: stats_result
    # - debug: msg={{stats_result}}

    - name: Rename nuxus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stats_result.stat.exists
